name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Create .nojekyll file
        run: echo > ./storybook-static/.nojekyll

      - name: Deploy Storybook to GitHub Pages
        run: npx gh-pages -d storybook-static
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
