name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Create .nojekyll file
        run: echo > ./storybook-static/.nojekyll

      - name: Deploy Storybook to GitHub Pages
        run: npm run deploy-storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
